if(EXISTS "C:/Users/aloha/Documents/GitHub/MIPS-Assembly-Simulator/build-headless/tests/unit_tests[1]_tests.cmake")
  include("C:/Users/aloha/Documents/GitHub/MIPS-Assembly-Simulator/build-headless/tests/unit_tests[1]_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
